"""empty message

Revision ID: 1d4043cc14b1
Revises: a4fc715b641b
Create Date: 2020-12-06 22:18:20.202652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4043cc14b1'
down_revision = 'a4fc715b641b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('show_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'artists', 'shows', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_column('artists', 'show_id')
    # ### end Alembic commands ###
