"""empty message

Revision ID: 2505184abaec
Revises: 1d4043cc14b1
Create Date: 2020-12-06 22:20:22.887826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2505184abaec'
down_revision = '1d4043cc14b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('show_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venues', 'shows', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'show_id')
    # ### end Alembic commands ###
