"""empty message

Revision ID: 55b504a3028c
Revises: 7b188b61b6f0
Create Date: 2020-12-08 23:11:29.686984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b504a3028c'
down_revision = '7b188b61b6f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'artist_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_image', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
