"""empty message

Revision ID: 5fe974104e88
Revises: 55b504a3028c
Create Date: 2020-12-08 23:14:57.716780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe974104e88'
down_revision = '55b504a3028c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'artist_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
