"""empty message

Revision ID: ad7a69bfb110
Revises: 5fe974104e88
Create Date: 2020-12-08 23:26:38.485339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7a69bfb110'
down_revision = '5fe974104e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.alter_column('genres', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'genres', 'venues', ['venue_id'], ['id'])
    op.drop_column('venues', 'website')
    op.drop_column('venues', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'genres', type_='foreignkey')
    op.alter_column('genres', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('genres', 'venue_id')
    # ### end Alembic commands ###
