"""empty message

Revision ID: d6c27b72a2f1
Revises: 21a776adf285
Create Date: 2020-12-12 21:18:41.370386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c27b72a2f1'
down_revision = '21a776adf285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.add_column('venues', sa.Column('image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'image_link')
    op.drop_column('artists', 'image_link')
    # ### end Alembic commands ###
