"""empty message

Revision ID: ea38dac278f2
Revises: 9fe168a4428f
Create Date: 2020-12-07 19:36:09.938392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea38dac278f2'
down_revision = '9fe168a4428f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artists_show_id_fkey', 'artists', type_='foreignkey')
    op.drop_column('artists', 'show_id')
    op.drop_constraint('venues_show_id_fkey', 'venues', type_='foreignkey')
    op.drop_column('venues', 'show_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('venues_show_id_fkey', 'venues', 'shows', ['show_id'], ['id'])
    op.add_column('artists', sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('artists_show_id_fkey', 'artists', 'shows', ['show_id'], ['id'])
    # ### end Alembic commands ###
